#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`
D1_CONF=/etc/dataone
NODE_PROPS="$D1_CONF/node.properties"

chmod +x /etc/init.d/d1-processing

update-rc.d d1-processing defaults 99



#these will need to be configured per environment
cp /usr/share/dataone-cn-processdaemon/debian/hazelcast.xml ${D1_CONF}/process/hazelcast.xml
cp /usr/share/dataone-cn-processdaemon/debian/synchronization.properties ${D1_CONF}/process/synchronization.properties
cp /usr/share/dataone-cn-processdaemon/debian/logAggregation.properties ${D1_CONF}/process/logAggregation.properties
cp /usr/share/dataone-cn-processdaemon/debian/replication.properties ${D1_CONF}/process/replication.properties
cp /usr/share/dataone-cn-processdaemon/debian/d1client.properties ${D1_CONF}/process/d1client.properties

HOSTNAME=$(/bin/hostname -f)

if [ "$HOSTNAME" != "" ]
then
  sed -i.bak  's/SERVER_NAME/'${HOSTNAME}'/' ${D1_CONF}/process/synchronization.properties
  sed -i.bak  's/SERVER_NAME/'${HOSTNAME}'/' ${D1_CONF}/process/logAggregation.properties
  sed -i.bak  's/SERVER_NAME/'${HOSTNAME}'/' ${D1_CONF}/process/d1client.properties
else
  log "HOSTNAME can not be set in ${D1_CONF}/process synchronization.properties,d1client.properties  or logAggregation.properties"
fi

# replace the IPs of the cn.iplist in node.properties so as to set them in hazelcast.xml
CN_IPLIST=`egrep 'cn.iplist=' ${NODE_PROPS}  | awk 'BEGIN { FS = "=" } ; { print $2 }'`
#add in commas
CN_IPLIST=${CN_IPLIST// /, }

sed -i.bak --regexp-extended "s/127\.0\.0\.1/${CN_IPLIST}/;" ${D1_CONF}/process/hazelcast.xml
 

chown -R tomcat6.tomcat6 /etc/dataone/process

cp /usr/share/dataone-cn-processdaemon/d1_process_daemon.jar /usr/share/java
chown -R tomcat6.tomcat6 /usr/share/java/d1_process_daemon.jar

##################################################################
# Set up logging for background processes
##################################################################
if [ ! -e "/var/log/dataone/daemon" ]
then
	mkdir  /var/log/dataone/daemon
	chown tomcat6.tomcat6 /var/log/dataone/daemon
fi

if [ ! -e "/var/log/dataone/synchronize" ]
then
	mkdir  /var/log/dataone/synchronize
	chown tomcat6.tomcat6 /var/log/dataone/synchronize
fi

if [ ! -e "/var/log/dataone/replicate" ]
then
	mkdir  /var/log/dataone/replicate
	chown tomcat6.tomcat6 /var/log/dataone/replicate
fi

if [ ! -e "/var/log/dataone/logAggregate" ]
then
	mkdir  /var/log/dataone/logAggregate
	chown tomcat6.tomcat6 /var/log/dataone/logAggregate
fi

#open up the correct port for hazelcast
ufw allow 5702 

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html

echo "Start Sychronization with /etc/init.d/d1-processing start"





